services:
  mongodb:
    image: mongo:7
    container_name: rewardhub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - rewardhub_mongodb_data:/data/db

volumes:
  rewardhub_mongodb_data:
